# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8090
  connection-timeout: 5000ms
  servlet:
    context-path: /pawn
security:
  basic:
    enabled: false
web:
  upload-path: /webapp/ #测试环境
#  upload-path: /Users/glavesoft/uploads/ #本地环境
#  upload-path: /opt/uploads/pawn/
spring:
  # 环境 dev|test|prod
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: 127.0.0.1
    port: 6379
    password: glavesoft    # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:templates/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path},/Users/glavesoft/uploads/pawn/
  freemarker:
    allow-request-override: false
    cache: true
    suffix: .html
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    request-context-attribute: request
  activemq:
    broker-url: tcp://180.76.186.228:61616
    in-memory: false      # 默认代理URL是否应该在内存中。如果指定了显式代理，则忽略此值。
    pool:
      enabled: true
      max-connections: 10
      idle-timeout: 30000ms
      expiry-timeout: 0ms
    packages:
      trust-all: true
  jms:
    pub-sub-domain: false


#  resources:
#    add-mappings: false


#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.pawn.glave.app.modules.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: AUTO
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'


renren:
  redis:
    open: false
  shiro:
    redis: false
  # APP模块，是通过jwt认证的，如果要使用APP模块，则需要修改【加密秘钥】
  jwt:
    # 加密秘钥
    secret: f4e2e52034348f86b67cde581c0f9eb5[paidang]
    # token有效时长，7天，单位秒
    expire: 604800
    header: token

wx:
  pay:
    app_id: wx1db6deeec2362999
    mch_id: 1600219091
    sercet: 2afb15cb32ba4fe6a0008eb629f4c051
    key: p6A4kILfG4iyDPJGHcRceDAAYb7qMEuW
    notify_url: http://180.76.186.228:8080/pawn/app/mini/pay/notify
    sign_type: MD5
    trade_type: JSAPI
    pay_url: https://api.mch.weixin.qq.com/pay/unifiedorder
